version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: benchmark
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
    ports:
      - '3306:3306'

  mongodb:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: